# Form implementation generated from reading ui file 'Demofinal1.4.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import serial.tools.list_ports
from PyQt6 import QtCore, QtGui, QtWidgets
import serial
import time
import threading
from PyQt6.QtCore import QObject, pyqtSignal

maxTemp = 38
maxUV = 4
maxAQI = 160

def read_from_serial(port, baudrate, timeout=1):
    ser = serial.Serial(port, baudrate, timeout=timeout)
    time.sleep(1)
    line = ser.readline().decode('utf-8', errors='ignore').strip()
    if line:
        data = [x for x in line.split(';')]
        return data
    else:
        return []

def available_ports():
    ports = serial.tools.list_ports.comports()
    
    available_ports = [port.device for port in ports]
    
    if not available_ports:
        msg=QtWidgets.QMessageBox()
        msg.setInformativeText("Khong co cong COM")
        msg.exec()

    return available_ports

class DataUpdater(QObject):
    update_data = pyqtSignal(list)
    stop_thread = False  # Flag to control the thread's behavior

    def __init__(self, parent=None):
        super().__init__(parent)

    def process_data(self, data):
        self.update_data.emit(data)

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 829)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 401, 721))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 121, 31))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 91, 41))
        self.label_8.setObjectName("label_8")
        self.COM = QtWidgets.QComboBox(parent=self.groupBox)
        self.COM.setGeometry(QtCore.QRect(138, 40, 151, 31))
        self.COM.setObjectName("COM")
        self.warning = QtWidgets.QTextEdit(parent=self.groupBox)
        self.warning.setGeometry(QtCore.QRect(20, 160, 271, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.warning.setFont(font)
        self.warning.setObjectName("warning")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 380, 55, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.Clear = QtWidgets.QPushButton(parent=self.groupBox)
        self.Clear.setGeometry(QtCore.QRect(30, 380, 241, 41))
        self.Clear.setObjectName("Clear")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 60, 331, 721))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 360, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Temp = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.Temp.setGeometry(QtCore.QRect(20, 80, 271, 87))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Temp.setFont(font)
        self.Temp.setObjectName("Temp")
        self.Humidity = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.Humidity.setGeometry(QtCore.QRect(20, 240, 271, 87))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Humidity.setFont(font)
        self.Humidity.setObjectName("Humidity")
        self.AQI = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.AQI.setGeometry(QtCore.QRect(20, 420, 271, 87))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.AQI.setFont(font)
        self.AQI.setObjectName("AQI")
        self.UV = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.UV.setGeometry(QtCore.QRect(10, 580, 271, 87))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.UV.setFont(font)
        self.UV.setObjectName("UV")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Clear.clicked.connect(self.ClearData)

        QtCore.QTimer.singleShot(100, self.start_read_data_thread)

    def start_read_data_thread(self):
        self.data_updater = DataUpdater()
        self.data_updater.update_data.connect(self.update_gui)

        self.read_data_thread = threading.Thread(target=self.read_data_worker)
        self.read_data_thread.daemon = True
        self.read_data_thread.start()

    def ClearData(self):
        self.Temp.clear()
        self.UV.clear()
        self.Humidity.clear()
        self.AQI.clear()
        self.warning.clear()

    def read_data_worker(self):
        while not self.data_updater.stop_thread:  
            com_ports = available_ports()
            self.COM.clear()
            self.COM.addItems(com_ports)

            com = str(self.COM.currentText())
            baudrate=115200
            data = None 
            if com:
                temp_data = read_from_serial(com, baudrate)  
                if temp_data:  
                    data = temp_data  
            print(data)
            if data:
                
                self.data_updater.process_data(data)
                

    def update_gui(self, data):
        if len(data) == 4:
            self.Temp.setText(str(data[0]))
            self.Humidity.setText(str(data[1]))
            self.UV.setText(str(data[2]))
            self.AQI.setText(str(data[3]))
            warnings=[]
            if float(data[0])>maxTemp:
                warnings.append("Nhiệt dộ cao. Cân nhắc bật điều hòa để giảm nhiệt độ")
            if float(data[2])>maxUV:
                warnings.append("Lượng UV lớn. Cân nhắc bật rèm che tia UV")
            if float(data[3])>maxAQI:
                warnings.append("Không khí chất lượng tệ. Cân nhắc bật máy lọc không khí")
            self.warning.setText("\n".join(warnings))


    def stop_read_data_thread(self):
        self.data_updater.stop_thread = True  
        self.read_data_thread.join()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.label_6.setText(_translate("MainWindow", "COM port:"))
        self.label_8.setText(_translate("MainWindow", "Warning"))
        self.Clear.setText(_translate("MainWindow", "Clear data"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Environment Data"))
        self.label_2.setText(_translate("MainWindow", "Temperature"))
        self.label_3.setText(_translate("MainWindow", "Humidity"))
        self.label_4.setText(_translate("MainWindow", "UV level"))
        self.label_5.setText(_translate("MainWindow", "Air Quality"))
        self.label.setText(_translate("MainWindow", "Smart Home Poject"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
